#
title: pinguozzo's blog
#  email: your-email@example.com
description: a place where I store what I do.
baseurl: "/gh-pages" # the subpath of your site, e.g. /blog
url: "pinguozzo.github.io"
twitter_username: pinguozzo
github_username: pinguozzo

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
